extend type ApiKey {
  """
  ✨ Implicit foreign key field based on `ApiKey`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "ApiKey.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Credit {
  """
  ✨ Implicit foreign key field based on `Credit`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Credit.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Referral {
  """
  ✨ Implicit foreign key field based on `Referral`.`referred`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  referredId: UUID! @fdc_generated(from: "Referral.referred", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Referral`.`referrer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  referrerId: UUID! @fdc_generated(from: "Referral.referrer", purpose: IMPLICIT_REF_FIELD)
}
extend type Transaction {
  """
  ✨ Implicit foreign key field based on `Transaction`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Transaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type UsageLog {
  """
  ✨ Implicit foreign key field based on `UsageLog`.`apiKey`. It must match the value of `ApiKey`.`id`. See `@ref` for how to customize it.
  """
  apiKeyId: UUID! @fdc_generated(from: "UsageLog.apiKey", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UsageLog`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UsageLog.user", purpose: IMPLICIT_REF_FIELD)
}
extend type UserSubscription {
  """
  ✨ Implicit foreign key field based on `UserSubscription`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserSubscription.user", purpose: IMPLICIT_REF_FIELD)
}
