extend type Mutation {
  """
  ✨ Insert a single `ApiKey` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  apiKey_insert(
    """
    Data object to insert into the table.
    """
    data: ApiKey_Data!
  ): ApiKey_KeyOutput! @fdc_generated(from: "ApiKey", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Credit` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  credit_insert(
    """
    Data object to insert into the table.
    """
    data: Credit_Data!
  ): Credit_KeyOutput! @fdc_generated(from: "Credit", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ModelPricing` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  modelPricing_insert(
    """
    Data object to insert into the table.
    """
    data: ModelPricing_Data!
  ): ModelPricing_KeyOutput! @fdc_generated(from: "ModelPricing", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Referral` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  referral_insert(
    """
    Data object to insert into the table.
    """
    data: Referral_Data!
  ): Referral_KeyOutput! @fdc_generated(from: "Referral", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Transaction` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transaction_insert(
    """
    Data object to insert into the table.
    """
    data: Transaction_Data!
  ): Transaction_KeyOutput! @fdc_generated(from: "Transaction", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UsageLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  usageLog_insert(
    """
    Data object to insert into the table.
    """
    data: UsageLog_Data!
  ): UsageLog_KeyOutput! @fdc_generated(from: "UsageLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserSubscription` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSubscription_insert(
    """
    Data object to insert into the table.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput! @fdc_generated(from: "UserSubscription", purpose: INSERT_SINGLE)
  """
  ✨ Insert `ApiKey` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  apiKey_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ApiKey_Data!]!
  ): [ApiKey_KeyOutput!]! @fdc_generated(from: "ApiKey", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Credit` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  credit_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Credit_Data!]!
  ): [Credit_KeyOutput!]! @fdc_generated(from: "Credit", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ModelPricing` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  modelPricing_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ModelPricing_Data!]!
  ): [ModelPricing_KeyOutput!]! @fdc_generated(from: "ModelPricing", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Referral` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  referral_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Referral_Data!]!
  ): [Referral_KeyOutput!]! @fdc_generated(from: "Referral", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Transaction` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transaction_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Transaction_Data!]!
  ): [Transaction_KeyOutput!]! @fdc_generated(from: "Transaction", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UsageLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  usageLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UsageLog_Data!]!
  ): [UsageLog_KeyOutput!]! @fdc_generated(from: "UsageLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserSubscription` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSubscription_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserSubscription_Data!]!
  ): [UserSubscription_KeyOutput!]! @fdc_generated(from: "UserSubscription", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `ApiKey` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ApiKey`.
  """
  apiKey_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ApiKey_Data!
  ): ApiKey_KeyOutput! @fdc_generated(from: "ApiKey", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Credit` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Credit`.
  """
  credit_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Credit_Data!
  ): Credit_KeyOutput! @fdc_generated(from: "Credit", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ModelPricing` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ModelPricing`.
  """
  modelPricing_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ModelPricing_Data!
  ): ModelPricing_KeyOutput! @fdc_generated(from: "ModelPricing", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Referral` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Referral`.
  """
  referral_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Referral_Data!
  ): Referral_KeyOutput! @fdc_generated(from: "Referral", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Transaction` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Transaction`.
  """
  transaction_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Transaction_Data!
  ): Transaction_KeyOutput! @fdc_generated(from: "Transaction", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UsageLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UsageLog`.
  """
  usageLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UsageLog_Data!
  ): UsageLog_KeyOutput! @fdc_generated(from: "UsageLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserSubscription` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSubscription`.
  """
  userSubscription_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput! @fdc_generated(from: "UserSubscription", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `ApiKey` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ApiKey`.
  """
  apiKey_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ApiKey_Data!]!
  ): [ApiKey_KeyOutput!]! @fdc_generated(from: "ApiKey", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Credit` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Credit`.
  """
  credit_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Credit_Data!]!
  ): [Credit_KeyOutput!]! @fdc_generated(from: "Credit", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ModelPricing` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ModelPricing`.
  """
  modelPricing_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ModelPricing_Data!]!
  ): [ModelPricing_KeyOutput!]! @fdc_generated(from: "ModelPricing", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Referral` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Referral`.
  """
  referral_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Referral_Data!]!
  ): [Referral_KeyOutput!]! @fdc_generated(from: "Referral", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Transaction` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Transaction`.
  """
  transaction_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Transaction_Data!]!
  ): [Transaction_KeyOutput!]! @fdc_generated(from: "Transaction", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UsageLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UsageLog`.
  """
  usageLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UsageLog_Data!]!
  ): [UsageLog_KeyOutput!]! @fdc_generated(from: "UsageLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserSubscription` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSubscription`.
  """
  userSubscription_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserSubscription_Data!]!
  ): [UserSubscription_KeyOutput!]! @fdc_generated(from: "UserSubscription", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `ApiKey` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ApiKey` or `null` if not found.
  """
  apiKey_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ApiKey_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ApiKey_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ApiKey_Data!
  ): ApiKey_KeyOutput @fdc_generated(from: "ApiKey", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Credit` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Credit` or `null` if not found.
  """
  credit_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Credit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Credit_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Credit_Data!
  ): Credit_KeyOutput @fdc_generated(from: "Credit", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ModelPricing` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ModelPricing` or `null` if not found.
  """
  modelPricing_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ModelPricing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModelPricing_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ModelPricing_Data!
  ): ModelPricing_KeyOutput @fdc_generated(from: "ModelPricing", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Referral` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Referral` or `null` if not found.
  """
  referral_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Referral_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Referral_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Referral_Data!
  ): Referral_KeyOutput @fdc_generated(from: "Referral", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Transaction` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Transaction` or `null` if not found.
  """
  transaction_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Transaction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Transaction_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Transaction_Data!
  ): Transaction_KeyOutput @fdc_generated(from: "Transaction", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UsageLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UsageLog` or `null` if not found.
  """
  usageLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UsageLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UsageLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UsageLog_Data!
  ): UsageLog_KeyOutput @fdc_generated(from: "UsageLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserSubscription` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserSubscription` or `null` if not found.
  """
  userSubscription_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSubscription_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSubscription_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput @fdc_generated(from: "UserSubscription", purpose: UPDATE_SINGLE)
  """
  ✨ Update `ApiKey` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  apiKey_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ApiKey_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ApiKey_Data!
  ): Int! @fdc_generated(from: "ApiKey", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Credit` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  credit_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Credit_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Credit_Data!
  ): Int! @fdc_generated(from: "Credit", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ModelPricing` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  modelPricing_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ModelPricing_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ModelPricing_Data!
  ): Int! @fdc_generated(from: "ModelPricing", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Referral` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  referral_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Referral_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Referral_Data!
  ): Int! @fdc_generated(from: "Referral", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Transaction` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  transaction_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Transaction_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Transaction_Data!
  ): Int! @fdc_generated(from: "Transaction", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UsageLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  usageLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UsageLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UsageLog_Data!
  ): Int! @fdc_generated(from: "UsageLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserSubscription` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userSubscription_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserSubscription_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserSubscription_Data!
  ): Int! @fdc_generated(from: "UserSubscription", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `ApiKey` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  apiKey_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ApiKey_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ApiKey_FirstRow
  ): ApiKey_KeyOutput @fdc_generated(from: "ApiKey", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Credit` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  credit_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Credit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Credit_FirstRow
  ): Credit_KeyOutput @fdc_generated(from: "Credit", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ModelPricing` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  modelPricing_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ModelPricing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModelPricing_FirstRow
  ): ModelPricing_KeyOutput @fdc_generated(from: "ModelPricing", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Referral` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  referral_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Referral_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Referral_FirstRow
  ): Referral_KeyOutput @fdc_generated(from: "Referral", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Transaction` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  transaction_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Transaction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Transaction_FirstRow
  ): Transaction_KeyOutput @fdc_generated(from: "Transaction", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UsageLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  usageLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UsageLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UsageLog_FirstRow
  ): UsageLog_KeyOutput @fdc_generated(from: "UsageLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserSubscription` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userSubscription_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSubscription_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSubscription_FirstRow
  ): UserSubscription_KeyOutput @fdc_generated(from: "UserSubscription", purpose: DELETE_SINGLE)
  """
  ✨ Delete `ApiKey` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  apiKey_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ApiKey_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ApiKey", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Credit` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  credit_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Credit_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Credit", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ModelPricing` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  modelPricing_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ModelPricing_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ModelPricing", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Referral` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  referral_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Referral_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Referral", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Transaction` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  transaction_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Transaction_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Transaction", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UsageLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  usageLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UsageLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UsageLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserSubscription` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userSubscription_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserSubscription_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserSubscription", purpose: DELETE_MULTIPLE)
}
