extend type Query {
  """
  ✨ Look up a single `ApiKey` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  apiKey(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ApiKey_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ApiKey_FirstRow
  ): ApiKey @fdc_generated(from: "ApiKey", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Credit` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  credit(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Credit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Credit_FirstRow
  ): Credit @fdc_generated(from: "Credit", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ModelPricing` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  modelPricing(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ModelPricing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModelPricing_FirstRow
  ): ModelPricing @fdc_generated(from: "ModelPricing", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Referral` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  referral(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Referral_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Referral_FirstRow
  ): Referral @fdc_generated(from: "Referral", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Transaction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  transaction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Transaction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Transaction_FirstRow
  ): Transaction @fdc_generated(from: "Transaction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UsageLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  usageLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UsageLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UsageLog_FirstRow
  ): UsageLog @fdc_generated(from: "UsageLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserSubscription` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userSubscription(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSubscription_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSubscription_FirstRow
  ): UserSubscription @fdc_generated(from: "UserSubscription", purpose: QUERY_SINGLE)
  """
  ✨ List `ApiKey` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  apiKeys(
    """
    Filter condition to narrow down the query results.
    """
    where: ApiKey_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ApiKey_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ApiKey_Having
  ): [ApiKey!]! @fdc_generated(from: "ApiKey", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Credit` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  credits(
    """
    Filter condition to narrow down the query results.
    """
    where: Credit_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Credit_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Credit_Having
  ): [Credit!]! @fdc_generated(from: "Credit", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ModelPricing` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  modelPricings(
    """
    Filter condition to narrow down the query results.
    """
    where: ModelPricing_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModelPricing_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModelPricing_Having
  ): [ModelPricing!]! @fdc_generated(from: "ModelPricing", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Referral` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  referrals(
    """
    Filter condition to narrow down the query results.
    """
    where: Referral_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Referral_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Referral_Having
  ): [Referral!]! @fdc_generated(from: "Referral", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Transaction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  transactions(
    """
    Filter condition to narrow down the query results.
    """
    where: Transaction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Transaction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Transaction_Having
  ): [Transaction!]! @fdc_generated(from: "Transaction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UsageLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  usageLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: UsageLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UsageLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UsageLog_Having
  ): [UsageLog!]! @fdc_generated(from: "UsageLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserSubscription` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userSubscriptions(
    """
    Filter condition to narrow down the query results.
    """
    where: UserSubscription_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserSubscription_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserSubscription_Having
  ): [UserSubscription!]! @fdc_generated(from: "UserSubscription", purpose: QUERY_MULTIPLE)
}
